# File: .github/workflows/dispatch-orchestrator.yml
name: Dispatch Orchestrator

on:
  workflow_call:
    inputs:
      proxy_api_url:
        required: true
        type: string
      event_type:
        required: true
        type: string
      source_branch:
        required: true
        type: string
    secrets:
      API_BEARER_TOKEN:
        required: true
        description: "Bearer token to authenticate with the orchestrator dispatcher proxy service"

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Call orchestrator via proxy
        run: |
          echo "Calling proxy URL: ${{ inputs.proxy_api_url }}"

          # Make the POST request, capture body and HTTP status
          RESPONSE=$(curl -s -w "%{http_code}" -o response.txt \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.API_BEARER_TOKEN }}" \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            "${{ inputs.proxy_api_url }}" \
            -d '{
                  "event_type": "'"${{ inputs.event_type }}"'",
                  "client_payload": {
                    "source_branch": "'"${{ inputs.source_branch }}"'"
                  }
                }')

          # Extract HTTP status code (last 3 digits)
          HTTP_CODE="${RESPONSE: -3}"

          # Print the response body
          cat response.txt

          # Fail workflow if HTTP code indicates error
          if [ "$HTTP_CODE" -ge 400 ]; then
            echo "Request failed with HTTP status $HTTP_CODE"
            exit 1
          fi