# File: .github/workflows/dispatch-orchestrator.yml
name: Dispatch Orchestrator

on:
  workflow_call:
    inputs:
      proxy_api_url:
        required: true
        type: string
      event_type:
        required: true
        type: string
      source_branch:
        required: true
        type: string
    secrets:
      API_BEARER_TOKEN:
        required: true
        description: "Bearer token to authenticate with the orchestrator dispatcher proxy service"

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Call orchestrator via proxy
        run: |
          curl -f -X POST \
            -H "Authorization: Bearer ${{ secrets.API_BEARER_TOKEN }}" \
            -H "Accept: application/json" \
            "${{ inputs.proxy_api_url }}" \
            -d "{
              \"event_type\": \"${{ inputs.event_type }}\",
              \"client_payload\": {
                \"source_branch\": \"${{ inputs.source_branch }}\"
              }
            }"
