name: Sync to App Repo

on:
  workflow_dispatch:
    inputs:
      source-branch:
        description: "Source branch to sync from"
        required: true
        default: "main"
      target-repo:
        description: "Owner/Repo of the target repository"
        required: true
      target-branch:
        description: "Target branch to sync to"
        required: true
        default: "main"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Ensure PAT exists
        run: |
          if [ -z "${{ secrets.DESTINATION_REPO_PAT }}" ]; then
            echo "❌ ERROR: DESTINATION_REPO_PAT secret is not set!"
            exit 1
          else
            echo "✅ PAT is provided"
          fi

      - name: Echo last 4 chars of PAT secret
        run: echo "${{ secrets.DESTINATION_REPO_PAT }}" | rev | cut -c1-4 | rev

      - name: Checkout source branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.source-branch }}

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add target repo with PAT
        run: git remote add target https://${{ secrets.DESTINATION_REPO_PAT }}:x-oauth-basic@github.com/${{ inputs.target-repo }}.git

      - name: Push code to target repo
        run: git push target HEAD:${{ inputs.target-branch }} --force