name: Sync Mono Repo Branch to Poly Repo

on:
  workflow_call:
    inputs:
      source-branch:
        description: "Source branch to sync from"
        required: true
        type: string
        default: "main"
      target-repo:
        description: "Owner/Repo of the target repository"
        required: true
        type: string
      target-branch:
        description: "Target branch to sync to"
        required: true
        type: string
        default: "main"
    secrets:
      DESTINATION_REPO_PAT:
        required: true

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure PAT exists
        run: |
          if [ -z "${{ secrets.DESTINATION_REPO_PAT }}" ]; then
            echo "❌ ERROR: DESTINATION_REPO_PAT secret is not set!"
            exit 1
          else
            echo "✅ PAT is provided"
          fi

      - name: Echo last 4 chars of PAT secret
        run: echo "${{ secrets.DESTINATION_REPO_PAT }}" | rev | cut -c1-4 | rev

      # 1. Checkout the source branch in the base repo
      - name: Checkout source branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.source-branch }}

      # 2. Clone the target repository
      - name: Clone target repository
        run: |
          git clone https://${{ secrets.DESTINATION_REPO_PAT }}@github.com/${{ inputs.target-repo }} target-repo

      # 3. Configure Git for automated commits/pushes
      - name: Configure Git
        run: |
          cd target-repo
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      # 4. Merge source branch into target repository branch
      - name: Merge source into target
        run: |
          cd target-repo
          # Checkout target branch or create if doesn't exist
          git fetch origin ${{ inputs.target-branch }} || true
          git checkout -B ${{ inputs.target-branch }} origin/${{ inputs.target-branch }} || git checkout -b ${{ inputs.target-branch }}
          # Pull changes from base repo (relative path)
          git pull ../ ${{ inputs.source-branch }} --allow-unrelated-histories

      # 5. Push merged changes to target repository
      - name: Push changes
        run: |
          cd target-repo
          git push origin ${{ inputs.target-branch }}

      # 6. Optional clean-up
      - name: Clean up local clone
        run: rm -rf target-repo
